# version: 2.1
# orbs:
#   aws-s3: circleci/aws-s3@3.0.0
# jobs:
#   build:
#     docker:
#       - image: cimg/node:16.10.0

#     working_directory: ~/repo

#     steps:
#       - checkout

#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             - v1-dependencies-
#       - run: yarn install

#       - save_cache:
#           paths:
#             - node_modules
#             - ~/.npm
#             - ~/.cache
#           key: v1-dependencies-{{ checksum "package.json" }}

#       - run: yarn test


#       - run: yarn build

#       - aws-s3/sync:
#           from: build
#           to: "s3://react-cicd-demo-github-action/"
#           arguments: |
#             --acl public-read \
#             --cache-control "max-age=86400"